const xmlStr =
  '<html dir="ltr"><head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style type="text/css">\r\n<!--\r\n-->\r\n</style></head><body><table dir="ltr"><tbody><tr><td id="i1" style="padding:0; font-family:\'Segoe UI Semibold\',\'Segoe UI Bold\',\'Segoe UI\',\'Helvetica Neue Medium\',Arial,sans-serif; font-size:17px; color:#707070">Microsoft account</td></tr><tr><td id="i2" style="padding:0; font-family:\'Segoe UI Light\',\'Segoe UI\',\'Helvetica Neue Medium\',Arial,sans-serif; font-size:41px; color:#2672ec">New app(s) have access to your data</td></tr><tr><td id="i3" style="padding:0; padding-top:25px; font-family:\'Segoe UI\',Tahoma,Verdana,Arial,sans-serif; font-size:14px; color:#2a2a2a">Graph Explorer connected to the Microsoft account <a dir="ltr" id="iAccount" class="link" href="mailto:te**2@outlook.com" style="color:#2672ec; text-decoration:none">te**2@outlook.com</a>.</td></tr><tr><td id="i4" style="padding:0; padding-top:25px; font-family:\'Segoe UI\',Tahoma,Verdana,Arial,sans-serif; font-size:14px; color:#2a2a2a">If you didn\'t grant this access, please remove the app(s) from your account.</td></tr><tr><td style="padding:0; padding-top:25px; font-family:\'Segoe UI\',Tahoma,Verdana,Arial,sans-serif; font-size:14px; color:#2a2a2a"><table border="0" cellspacing="0"><tbody><tr><td bgcolor="#2672ec" style="background-color:#2672ec; padding-top:5px; padding-right:20px; padding-bottom:5px; padding-left:20px; min-width:50px"><a id="i5" href="https://account.live.com/consent/Manage?fn=email" style="font-family:\'Segoe UI Semibold\',\'Segoe UI Bold\',\'Segoe UI\',\'Helvetica Neue Medium\',Arial,sans-serif; font-size:14px; text-align:center; text-decoration:none; font-weight:600; letter-spacing:0.02em; color:#fff">Manage your apps</a></td></tr></tbody></table></td></tr><tr><td id="i6" style="padding:0; padding-top:25px; font-family:\'Segoe UI\',Tahoma,Verdana,Arial,sans-serif; font-size:14px; color:#2a2a2a">You can also <a id="iLink3" class="link" href="https://account.live.com/SecurityNotifications/Update" style="color:#2672ec; text-decoration:none">opt out</a> or change where you receive security notifications.</td></tr><tr><td id="i7" style="padding:0; padding-top:25px; font-family:\'Segoe UI\',Tahoma,Verdana,Arial,sans-serif; font-size:14px; color:#2a2a2a">Thanks,</td></tr><tr><td id="i8" style="padding:0; font-family:\'Segoe UI\',Tahoma,Verdana,Arial,sans-serif; font-size:14px; color:#2a2a2a">The Microsoft account team</td></tr></tbody></table><div lang="en" style="margin-top:20px; margin-bottom:10px"><a class="link" href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy Statement</a><div style="margin-top:10px">Microsoft Corporation, One Microsoft Way, Redmond, WA 98052</div></div></body></html>';

const testEle = document.createElement("div");

testEle.innerHTML = xmlStr;

document.body.append(testEle);

// const body = document.getElementsByTagName("body");
